### PR TITLE
Fix select() by space_no and index_name

### LINKED ISSUE #42: Internal error on select by a space id and an index name
``` php
const SPACE_INDEX = 288;
(new Tarantool())->select(SPACE_INDEX, [], 'name');
```

fails with:

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Internal Error' ...
```

### PR DESCRIPTION
**Pull request by bigbes**
When a space exists, but a client side schema does not know about it at
the moment (say, right after connection), and when a user calls select()
with a space id (number) and name of an index (string), the problem
appears: the client raises the following error:

```
TarantoolParsingException: Failed to parse schema (index)
```

However it should successfully perform the request.

The problem is that when there is no record for a space in client's
schema, it is not possible to save a record for an index of this space.

The idea of the fix is to verify whether we know about a space even when
a numeric ID is already provided. If a client has no record about the 
space, it fetches a schema and verify whether the space appears. If so, 
there is no more problem described above. Otherwise the client raises an
error that the space with given ID does not exist.

While we're here, ensure that return values of tarantool_schema_*() are 
checked against -1, not Zend's FAILURE macro (which is only guaranteed
to be less than zero) in the modified code. Also ensure that the FAILURE
macro is returned from the get_spaceno_by_name() function, not -1. 

Closes #42

### CODE REVIEW

File: src/tarantool_schema.c [hunk 1]
```diff
@@ -398,6 +398,21 @@ schema_add_space(
 	return -1;
 }
 
+int
+tarantool_schema_has_space_no(
```
Comment (Totktonada) [inline src/tarantool_schema.c]: It seems it is not used.

File: src/tarantool_schema.c [hunk 2]
```diff
@@ -557,6 +572,25 @@ tarantool_schema_get_sid_by_string(
 	return space->space_number;
 }
 
+/* ALIAS for verify existens */
```
Comment (Totktonada) [inline src/tarantool_schema.c]: What do you mean? That we can check whether the space exists by `sid` using this function?

File: src/tarantool_schema.c (hunk 1 above)
Comment (eljashm) [reply src/tarantool_schema.c:402]: Confirmed that it is not used and removed.

File: src/tarantool_schema.c (hunk 2 above)
Comment (eljashm) [reply src/tarantool_schema.c:575]: Removed misleading comment.

File: src/tarantool.c [hunk 3]
```diff
@@ -679,10 +689,22 @@ int get_spaceno_by_name(tarantool_connection *obj, zval *name) {
...
-	space_no = tarantool_schema_get_sid_by_string(obj->schema,
-			Z_STRVAL_P(name), Z_STRLEN_P(name));
-	if (space_no == FAILURE)
-		THROW_EXC("No space '%s' defined", Z_STRVAL_P(name));
+
+	if (Z_TYPE_P(name) == IS_LONG) {
+		space_no = tarantool_schema_get_sid_by_number(obj->schema,
+							      Z_LVAL_P(name));
+		if (space_no == FAILURE) {
+			THROW_EXC("No space '%s' defined", Z_STRVAL_P(name));
```
Comment (Totktonada) [inline src/tarantool.c:697]: It is a long value, not a string. Causes a segfault in case of select using an unknown space id.

File: src/tarantool.c [hunk 4]
```diff
@@ -679,10 +689,22 @@ int get_spaceno_by_name(tarantool_connection *obj, zval *name) {
...
+		}
+	} else {
+		space_no = tarantool_schema_get_sid_by_string(obj->schema,
+							      Z_STRVAL_P(name),
+							      Z_STRLEN_P(name));
+		if (space_no == FAILURE) {
+			THROW_EXC("No space '%ul' defined", Z_LVAL_P(name));
```
Comment (Totktonada) [inline src/tarantool.c:704]: It is a string, not a long value.

File: src/tarantool.c [hunk 5]
```diff
@@ -660,10 +669,11 @@ int get_spaceno_by_name(tarantool_connection *obj, zval *name) {
 	size_t body_size = php_mp_unpack_package_size(pack_len);
 	smart_string_ensure(obj->value, body_size);
 	if (tarantool_stream_read(obj, obj->value->c,
-				body_size) == FAILURE)
+				  body_size) == FAILURE)
```
Comment (Totktonada) [inline src/tarantool.c:672]: Unrelevant diff.

File: src/tarantool.c [hunk 6]
```diff
@@ -660,10 +669,11 @@ int get_spaceno_by_name(tarantool_connection *obj, zval *name) {
...
 		return FAILURE;
 
-	struct tnt_response resp; memset(&resp, 0, sizeof(struct tnt_response));
+	struct tnt_response resp;
+	memset(&resp, 0, sizeof(struct tnt_response));
```
Comment (Totktonada) [inline src/tarantool.c:676]: Unrelevant diff (here and below).

File: src/tarantool_schema.c [hunk 7]
```diff
@@ -557,6 +557,24 @@ tarantool_schema_get_sid_by_string(
...
+int32_t
+tarantool_schema_get_sid_by_number(
+		struct tarantool_schema *schema_obj,
+		uint32_t sid
+) {
+	struct mh_schema_space_t *schema = schema_obj->space_hash;
+	struct schema_key space_key = {
+		(void *)&sid,
+		sizeof(uint32_t), 0
+	};
```
Comment (Totktonada) [inline src/tarantool_schema.c:569]: Cast of `uint32 *` to `const char *` (via `void *`). Looks very strange.

File: test/DMLTest.php [hunk 8]
```diff
@@ -468,4 +468,13 @@ public function test_18_02_delete_loop() {
         gc_collect_cycles();
         gc_collect_cycles();
     }
+
+	/**
+	 * @doesNotPerformAssertions
+	 */
+	public function test_19_schema_obtain_failed() {
+        $port = TestHelpers::getTarantoolPort();
+		$empty_tarantool = new Tarantool('localhost', $port, 'test');
```
Comment (Totktonada) [inline test/DMLTest.php:477]: `test` password is forgotten.

Comment (Totktonada) [inline test/DMLTest.php:477]: The problem appears only when there is no fetched schema. It is not obvious from the testing code and should be clarified in a comment.

File: src/tarantool.c [hunk 9]
```diff
@@ -696,6 +718,7 @@ int get_indexno_by_name(tarantool_connection *obj, int space_no,
 		THROW_EXC("Index ID must be String or Long");
 		return FAILURE;
 	}
+
```
Comment (Totktonada) [inline src/tarantool.c:721]: Unrelevant change.

File: src/tarantool.c [hunk 10]
```diff
@@ -631,21 +631,30 @@ int convert_iterator(zval *iter, int all) {
 }
 
 int get_spaceno_by_name(tarantool_connection *obj, zval *name) {
-	if (Z_TYPE_P(name) == IS_LONG)
-		return Z_LVAL_P(name);
-	if (Z_TYPE_P(name) != IS_STRING) {
+	if (Z_TYPE_P(name) != IS_STRING && Z_TYPE_P(name) != IS_LONG) {
```
Comment (Totktonada) [inline src/tarantool.c:634]: It is strange. We already know space id, wy should we fetch schema in the case?

The problem root is that we check whether a schema is actual only at space nmae resolving, but not in index name resolving. I would just check it in the both places.

File: test/DMLTest.php (hunk 8 above)
Comment (Totktonada) [inline test/DMLTest.php:477]: Mix of tabs and spaces.

File: src/tarantool.c (hunk 10 above)
Comment (Totktonada) [reply src/tarantool.c:634]: OTOH, if we'll verify whether a space exist here, we'll give more proper error if it does not exist. Say, not `No index 'name' defined`, but `No space 1024 defined`.

File: src/tarantool_schema.c (hunk 7 above)
Comment (Totktonada) [reply src/tarantool_schema.c:569]: Got it. Both numeric and string values are compared just as byte arrays without taking its types into account.

A clash is possible in theory: say, valid space name `!!!!` is the same as a [valid](https://www.tarantool.io/en/doc/1.10/book/box/limitations/) space id 555819297 (0x21212121). The minimal uint32_t number that corresponds to a valid space name (four spaces) is 538976288 (0x20202020) if we'll choose printable characters from ASCII. I'm not sure whether it is possible to find a clash with lower space id using unicode printable symbols.

It is not sane, but it seems it should work in practice.

BTW, just observed that the last structure field (`number`) is not left uninitialized. It is initialized as zero, but the field is not used anywhere, so it does not matter. If we'll use it, however, it seems logical to set it in the similar way as other code do (see `schema_add_index()`). I mean, set it to a space id.

File: src/tarantool.c (hunk 10 above)
Comment (Totktonada) [reply src/tarantool.c:634]: > The problem root is that we check whether a schema is actual only at space name resolving, but not in index name resolving. I would just check it in the both places.

I found that it is not accurate, shame on me. We actually fetch an index information in the case, but `schema_add_index()`, which adds the index info assumes that a space information already present.

File: test/DMLTest.php (hunk 8 above)
Comment (Totktonada) [reply test/DMLTest.php:477]: It seems, if only username is passed (but no password) the client will silently connect as 'guest' user without a password. What a hell…

If I change the following `&&` to `||`:

https://github.com/tarantool/tarantool-php/blob/e67cb231d48219d1f01cf1e5b4c3cc93d8004f9f/src/tarantool.c#L309

Then I got `TarantoolClientError: Invalid MsgPack - authentication request body`.

That's all looks as a bug.

File: src/tarantool.c (hunk 10 above)
Comment (Totktonada) [reply src/tarantool.c:634]: Okay, left the approach as is. Providing an adequate error message is important point.

File: src/tarantool.c (hunk 3 above)
Comment (Totktonada) [reply src/tarantool.c]: Fixed.

File: src/tarantool.c (hunk 4 above)
Comment (Totktonada) [reply src/tarantool.c]: Fixed.

File: src/tarantool.c (hunk 5 above)
Comment (Totktonada) [reply src/tarantool.c]: Reverted the change.

File: src/tarantool.c (hunk 6 above)
Comment (Totktonada) [reply src/tarantool.c]: Reverted all such changes.

File: src/tarantool_schema.c (hunk 7 above)
Comment (Totktonada) [reply src/tarantool_schema.c]: Nothing to do, closing.

File: test/DMLTest.php (hunk 8 above)
Comment (Totktonada) [reply test/DMLTest.php]: Fixed. I'll file a separate issue re behaviour when a password is not provided.

Comment (Totktonada) [reply test/DMLTest.php]: Clarified.

File: src/tarantool.c (hunk 9 above)
Comment (Totktonada) [reply src/tarantool.c]: Reverted.

File: test/DMLTest.php (hunk 8 above)
Comment (Totktonada) [reply test/DMLTest.php]: Fixed.

**Comment by Totktonada** [comment]
@LeonidVas Please, look at this briefly if time permits. I think the patch in the good state now, but it would be good if you'll glance.

File: test/DMLTest.php (hunk 8 above)
Comment (Totktonada) [reply test/DMLTest.php]: Filed #165.

**Comment by LeonidVas** [comment]
> @LeonidVas Please, look at this briefly if time permits. I think the patch in the good state now, but it would be good if you'll glance.

Hi! @bigbes , thank you for the PR. Generally LGTM.
But I'm confused by mixing FAILURE from the ZEND_RESULT_CODE enum and -1.
We don't have any guarantee that it will always be -1 and can't check -1 == FAILURE. From a comment to ZEND_RESULT_CODE: "this MUST stay a negative number", not exactly -1. On the other hand, I agree that such things rarely change. So, Up to you @Totktonada .

**Comment by Totktonada** [comment]
@LeonidVas I agree. Fixed and added the following paragraph into the commit message:

> While we're here, ensure that return values of tarantool_schema_*() are
> checked against -1, not Zend's FAILURE macro (which is only guaranteed
> to be less than zero) in the modified code. Also ensure that the FAILURE
> macro is returned from the get_spaceno_by_name() function, not -1.
